import React, { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import { Header, Filterbar } from "../components";
import { CountriesList } from "../components/CountriesList/CountriesList";
import { getCountries, getContinents } from "./api/CountriesAPI";
import { Country } from "../components/types";

const Home: NextPage = () => {
  const [countries, setCountries] = useState([] as Country[]);
  const [unfiltered, setUnfiltered] = useState([]);
  const [continents, setContinents] = useState([]);
  const countriesAPI = getCountries();
  const continentsAPI = getContinents();

  useEffect(() => {
    if (countriesAPI.data) {
      setCountries(countriesAPI.data.countries);
      setUnfiltered(countriesAPI.data.countries);
    }
  }, [countriesAPI.loading]);

  useEffect(() => {
    if (continentsAPI.data) {
      setContinents(continentsAPI.data.continents);
    }
  }, [continentsAPI.loading]);

  return (
    <>
      <Head>
        <title>Country Locator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="fixed top-0 z-10 w-full">
        <Header />
        <Filterbar
          setCountries={setCountries}
          countries={unfiltered}
          continents={continents}
        />
      </div>
      <CountriesList data={countries} loading={countriesAPI.loading} />
    </>
  );
};

export default Home;
